### ISSUE TITLE
Support for Go 1.23.1 or higher in the Docker image

### ISSUE THREAD

**Issue by jaimeyh** [qbaware/nilaway-action#22]
I'm currently using this GitHub Action, but it is based on a Docker image with Go 1.22. However, my project requires Go 1.23.1 or higher, as specified in the go.work file, and I'm encountering errors when running the action due to this version mismatch.

The error message is as follows:
```go
stderr: go: go.work requires go >= 1.23.1 (running go 1.22.0; GOTOOLCHAIN=local)
```
Could you please update the Docker image to include Go 1.23.1 or later? This would greatly improve compatibility with projects using newer versions of Go.

Alternatively, if there is another way to make the action work without updating the Docker image, I would be open to exploring that option as well.

Thank you for your consideration!

**Comment by danielgospodinow** [comment]
Hey there, @jaimeyh! Sure, sorry for the inconvenience. I'll make sure to update some deps around the project in a couple of hours.

I'll post an update here on the issue once I do all this. 😄

**Comment by danielgospodinow** [comment]
Closed with https://github.com/qbaware/nilaway-action/pull/20

**Comment by danielgospodinow** [comment]
A new `0.0.11` version has been released. Give it a try and let me now if it now works for you, @jaimeyh.

**Comment by jaimeyh** [comment]
Thank you so much @danielgospodinow now the issue related with version is fixed. 
I'm still having some other issues but is not related with that. 😅 
P.S. Could I reach you by mail or some other way and ask you about these other issues (I think are not related with the action)?

**Comment by danielgospodinow** [comment]
Nice, glad to hear! 👏🏼 

Sure! So whatever works for you: 
- [LinkedIn](https://www.linkedin.com/in/danielgospodinow/) 
- Qbaware's [Discord](https://discord.gg/FH6rdybQ)  
- DM in Discord: danielgospodinow#4666

Let's see if I can help out. 😄
